### ISSUE TITLE
Ekey decoder can speak with iobroker ?

### ISSUE THREAD

**Issue by mikewolf** [tuxedo0801/ekeydecoder#1]
Hello ,i have a question about ekeydecoder .
can you help me ?, i use the ekeydecoder tool it works perfect for me ,but i had no Knx .
i have a Hpgen8 with various VM`s , one of this with the great projekt IOBROKER,
is there any chance to communicate ioroker with ekeydecoder ?

with best regards mikewolf

**Comment by tuxedo0801** [comment]
Hey Mike,

either you change the ekeydecoder implementation to speak something iobroker is able to understand, or you find a way to interface KNX by software to iobroker.
Check for example https://github.com/knxd/knxd
knxd is able to receive the commands ekeydecoder is sending. With that you should be able to write scripts that listen for ekeydecoder messages and transform them into something else. 

br,
alex

**Comment by mikewolf** [comment]
Hallo , habe leider problem , habe Kxnd installiert , mit groupswrite kommt die Meldung in ETS an
sowohl als Gruppenmeldung und auch als Busmeldung , nur leider schaffe ich es nicht,
 den ekeydecoder fingerhash in richtung ETS Gruppenmeldung oder busmeldung zu bekommen ?
habe x seiten gelesen ... irgendwie komme ich nicht weiter ?! 
BITTE um Hilfe
